version: '3.8'
services:
  mysql:
    image: mysql:8
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ecommerce

  auth-service:
    build: ./auth-service
    ports:
      - "8081:8081"
    depends_on:
      - mysql

  catalog-service:
    build: ./catalog-service
    ports:
      - "8082:8082"
    depends_on:
      - mysql

  order-service:
    build: ./order-service
    ports:
      - "8083:8083"
    depends_on:
      - mysql

  payment-service:
    build: ./payment-service
    ports:
      - "8084:8084"
    depends_on:
      - mysql

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - auth-service
      - catalog-service
      - order-service
      - payment-service